/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedSharedWithMeRouteImport } from './routes/_authenticated/shared-with-me'
import { Route as AuthenticatedDriveIndexRouteImport } from './routes/_authenticated/drive.index'
import { Route as AuthenticatedDriveFolderIdRouteImport } from './routes/_authenticated/drive.$folderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSharedWithMeRoute =
  AuthenticatedSharedWithMeRouteImport.update({
    id: '/shared-with-me',
    path: '/shared-with-me',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriveIndexRoute = AuthenticatedDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriveFolderIdRoute =
  AuthenticatedDriveFolderIdRouteImport.update({
    id: '/drive/$folderId',
    path: '/drive/$folderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shared-with-me': typeof AuthenticatedSharedWithMeRoute
  '/drive/$folderId': typeof AuthenticatedDriveFolderIdRoute
  '/drive/': typeof AuthenticatedDriveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shared-with-me': typeof AuthenticatedSharedWithMeRoute
  '/drive/$folderId': typeof AuthenticatedDriveFolderIdRoute
  '/drive': typeof AuthenticatedDriveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/shared-with-me': typeof AuthenticatedSharedWithMeRoute
  '/_authenticated/drive/$folderId': typeof AuthenticatedDriveFolderIdRoute
  '/_authenticated/drive/': typeof AuthenticatedDriveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shared-with-me' | '/drive/$folderId' | '/drive/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shared-with-me' | '/drive/$folderId' | '/drive'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/shared-with-me'
    | '/_authenticated/drive/$folderId'
    | '/_authenticated/drive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shared-with-me': {
      id: '/_authenticated/shared-with-me'
      path: '/shared-with-me'
      fullPath: '/shared-with-me'
      preLoaderRoute: typeof AuthenticatedSharedWithMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive/': {
      id: '/_authenticated/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof AuthenticatedDriveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive/$folderId': {
      id: '/_authenticated/drive/$folderId'
      path: '/drive/$folderId'
      fullPath: '/drive/$folderId'
      preLoaderRoute: typeof AuthenticatedDriveFolderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSharedWithMeRoute: typeof AuthenticatedSharedWithMeRoute
  AuthenticatedDriveFolderIdRoute: typeof AuthenticatedDriveFolderIdRoute
  AuthenticatedDriveIndexRoute: typeof AuthenticatedDriveIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSharedWithMeRoute: AuthenticatedSharedWithMeRoute,
  AuthenticatedDriveFolderIdRoute: AuthenticatedDriveFolderIdRoute,
  AuthenticatedDriveIndexRoute: AuthenticatedDriveIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
